- name: Jasa Pembuatan Aplikasi Web
  message_text: Halo Min, saya perlu jasa pembuatan aplikasi web. Bisa diskusi sebentar?

- name: Jasa Desain Database
  message_text: Halo Min, saya perlu jasa desain database. Bisa diskusi sebentar?

